### ISSUE TITLE
ci:  upgrade to trusted publisher

### ISSUE THREAD

**Issue by mj0nez** [mj0nez/bdew-datetimes#151]
```
Upgrade to Trusted Publishing
Trusted Publishers allows publishing packages to PyPI from automated environments like GitHub Actions without needing to use username/password combinations or API tokens to authenticate with PyPI. Read more: https://docs.pypi.org/trusted-publishers

```

https://github.com/mj0nez/bdew-datetimes/actions/runs/10057052339

**Comment by hf-kklein** [comment]
I opened a PR for the adjustments in the CI workflow: #152 
You need to do few small steps in the Pypi UI:

- [ ] Merge #152
- [ ] create an enviroment with name "release" here: https://github.com/mj0nez/bdew-datetimes/settings/environments
- [ ] Visit: https://pypi.org/manage/project/bdew-datetimes/settings/publishing/
- [ ] Fill out the publishers info with your repo details:
![grafik](https://github.com/user-attachments/assets/cf6baff0-1540-4356-9130-5c284a13501f)
- [ ] create a new release in this repo, just like before

**Comment by mj0nez** [comment]
![](https://j.gifs.com/vqgLDE.gif)

Thank you!
