### ISSUE TITLE
Release with Python 3.13 Support

### ISSUE THREAD

**Issue by hf-kklein** [mj0nez/bdew-datetimes#180]
Hi, könntest du bitte eine Release erstellen mit dem offiziellen 3.13 Support aus #179? Ich baue gerade teile unserer fristenkalender pipeline auf 3.13 um und würde das dann als min-version einstellen. danke!

**Comment by mj0nez** [comment]
Done [0.7.0](https://github.com/mj0nez/bdew-datetimes/releases/tag/v0.7.0) :)
