### ISSUE TITLE
Is this package published on PyPi already?

### ISSUE THREAD

**Issue by hf-kklein** [mj0nez/bdew-datetimes#3]
Hi @mj0nez,
we'd love to use this library but it seems like it is not available on PyPi?
https://pypi.org/search/?q=+energy-datetime-utils&o=

Do you plan to publish it there? I see two options:
1. we could either fork it and publish it from our (@Hochfrequenz / [unlimitedfox](https://pypi.org/user/unlimitedfox/)) account
2. or we could help you setup the deployment pipeline. It's pretty straightforward, once you've done it a few times. Shouldn't take more than 10mins.

Just drop a line what you'd prefer and we're happy to help :)

BTW: If you're publishing it on your own PyPi account I'd suggest to not call it "energy-datetime-utils" but instead be very specific with e.g. "bdewholidays" or something similar. That'd make it obvious to anyone whom it may concern what exactly the thing does while "energy" is quite vague.

**Comment by mj0nez** [comment]
Hi,

I’m very sorry to get back to you this late. It seems, that my notification rules need some adjustments.
Glad you are interested in the project! Unfortunately, I haven’t published it yet, because of some other assignments and my intention to add some further functionality. 

As you’ve already submitted some PRs to set up the project for publishing, I’ll get on to this ASAP and keep you posted.
Any information on deployment pipelines would be appreciated! :)

RE the projects name: You are right, it is too vague for its current use cases. I’ll consider this before publishing!

Again, sorry for the radio silence and a happy new year!

**Comment by hf-kklein** [comment]
Hi @mj0nez,
thanks for your answer. Here's what I'd suggest to proceed (in this order):

### 1. Basic Project Settings
- Specify requirements #1 
- Enforce black formatting #4
- Sort imports #7 

### 2. Set up Quality Gates (CI)
- Introduce tox and automatically run tests on all PRs #2 
- Introduce pylint as a linter #5 
- Introduce static type checking #8 

### 3. Release Preparations and Directory Structure Adjustments
After the basic setup (and ideally not before to avoid merge conflicts) I'd suggest to
- [ ] Rename the directory `energy_datetime` to `bdew_calendar` (as discussed above)
- [ ] Rename this repo in its settings
- [ ] Use a [src-based layout](https://packaging.python.org/en/latest/discussions/src-layout-vs-flat-layout/) instead of a flat layout (might require minor adjustments in your IDE settings [like this](https://github.com/Hochfrequenz/python_template_repository#how-to-use-with-pycharm)
- [ ] Test the packaging process in a tox environment and modify setup.py accordingly #9
- [ ] Get yourself an API token on PyPi and store it in the [repo secrets](https://github.com/mj0nez/energy-datetime-utils/settings/secrets/actions) as `PYPI_API_TOKEN`

### 4. The actual release workflow
- [ ] Create a Github Action to trigger the release workflow (see e.g. [here](https://github.com/Hochfrequenz/mig_ahb_utility_stack/blob/main/.github/workflows/python-publish.yml))
- [ ] Create a release [here](https://github.com/mj0nez/energy-datetime-utils/releases/new)

Happy to help. I can proceed as soon as you merged the first 7 PRs ;)

**Comment by hf-kklein** [comment]
Done 🎉https://pypi.org/project/bdew-datetimes/
